# Generated by Django 2.1.5 on 2019-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
                ('profile_pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
