# Generated by Django 2.1.7 on 2019-02-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
