# Generated by Django 2.1.7 on 2019-02-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Unlisted', editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Category'),
        ),
    ]
