# Generated by Django 2.1.7 on 2019-02-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_post_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
