# Generated by Django 2.1.7 on 2019-02-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190225_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='caption',
        ),
    ]
